### ISSUE TITLE
Dbus

### ISSUE THREAD

**Issue by soumyaDghosh** [nlogozzo/NickvisionTubeConverter#51]
Does your app  need to access the dbus? If no then I will remove it from the snap.

**Comment by nlogozzo** [comment]
@fsobolev

**Comment by fsobolev** [comment]
No, it doesn't need dbus access, only graphics (wayland/x11), network and files. For files, I don't know how files access is managed in snap, so maybe you will need to give access to home and removable media.

**Comment by soumyaDghosh** [comment]
Everything is fine anyway, I was just asking about dbus, because for snaps, to get access of dbus, you need to pass a manual review.

**Comment by nlogozzo** [comment]
@fsobolev I suppose with `rc1`, now it needs dbus.

**Comment by fsobolev** [comment]
> @fsobolev I suppose with `rc1`, now it needs dbus, or no?

I guess no. But it depends on what dbus access means in the context of snap.
Pardon me if I'm going to say bs further, I didn't read much documentation on discussed topics, but that's how I understand things work. If there are mistakes in my understanding and somebody can point them out, I will be grateful.
In flatpak dbus access is required to let the program make calls on an accessed bus. We don't do this in TC and that's why there's nothing dbus-related in the manifest. What TC does is the opposite: it provides dbus service to allow other programs to make calls on TC. Thanks to this the app's window gets focused when a user clicks on a notification, for example.
